### ISSUE TITLE
remark-rehype and rehype-stringify are not listed as dependencies

### ISSUE THREAD

**Issue by furrykef** [landakram/remark-wiki-link#1]
My project does not use remark-rehype directly, so I didn't have it or rehype-stringify installed. I think these two packages should be marked as dependencies because remark-wiki-link will not function without them.

**Comment by wwtex** [comment]
It seems these `remark-rehype` and `rehype-stringify` aren't actually depended on by the plugin itself, but used by unremoved test code.

**Comment by landakram** [comment]
Thanks for reporting :) this is fixed as of `v0.0.3`.
