### ISSUE TITLE
It's crashing on build

### ISSUE THREAD

**Issue by Utkarshbhimte** [landakram/remark-wiki-link#20]
I am trying to implement this to my nextjs blog, so I can easily deploy my obsidian notes. 

This is the error I am getting when I trigger the build 
<img width="938" alt="CleanShot 2021-09-10 at 17 01 03@2x" src="https://user-images.githubusercontent.com/13379773/132847026-d965215f-fb91-4744-b8ea-e18df0880bec.png">

This is my implementation
```js
  const { code, frontmatter } = await bundleMDX(source, {
    xdmOptions(options) {
      options.remarkPlugins = [
        ...(options?.remarkPlugins ?? []),
        remarkGfm,
        [
          wikiLinkPlugin,
          {
            hrefTemplate: permalink => permalink && `/blog/${permalink}` || '',
            pageResolver: (name) => name?.replaceAll(' ', '-')?.toLowerCase()
          }
        ]
      ];
      options.rehypePlugins = [
        ...(options?.rehypePlugins ?? []),
        rehypeSlug,
        rehypeCodeTitles,
        rehypePrism,
        [
          rehypeAutolinkHeadings,
          {
            properties: {
              className: ['anchor']
            }
          }
        ]
      ];
      return options;
    }
  });
```

also the md files also look like this 
<img width="977" alt="CleanShot 2021-09-10 at 17 02 38@2x" src="https://user-images.githubusercontent.com/13379773/132847226-0deef0a6-cf9b-4708-a023-813dbbb528e3.png">

I tried googling the error but couldn't find anything relevant. 
Any help would be appreciated, thanks 😊

**Comment by landakram** [comment]
Can you share how you’re importing `wikiLinkPlugin`? The stack trace makes me think it's related to my fix for this issue https://github.com/landakram/remark-wiki-link/issues/12

If you're using a default import, can you try a destructured import and see if that changes anything?

```typescript
import {wikiLinkPlugin} from "remark-wiki-link"
```

And, congrats on your new jpeg 😛

**Comment by Utkarshbhimte** [comment]
I think it's more related to https://github.com/kentcdodds/mdx-bundler/issues/93


> And, congrats on your new jpeg 😛

Sorry, I missed the reference here, is it because of the screenshots? 😅

**Comment by landakram** [comment]
Ah okay, I’ll close this issue then, as the one you linked doesn’t seem specific to this plugin. 

> Sorry, I missed the reference here, is it because of the screenshots?

It was in reference to the seven NFT drop 😄
