### ISSUE TITLE
Thoughts on a similar mdast utility

### ISSUE THREAD

**Issue by aegatlin** [landakram/remark-wiki-link#23]
Hello, I am reaching out because I am considering using a wiki-link utility in a similar transform space of `md -> hast`. However, I am quite keen on the idea of handling wiki-links within the md space, fully ignorant of html, hast, etc. So, a `md -> md` utility. For example,

```
This is [[markdown]] content.
```

would become

```
This is [markdown](./path/to/markdown.md) content.
```

or

```
This is [markdown(https://example.com/path/to/markdown) content.
```

This would lack many of the features of your utility, but would also allow for `md -> md` use cases. If you considered this path, I'd be curious to hear why you decided against it. And happy to hear any thoughts you have on this issue more generally. I would be happy to contribute to any utilities that you think are amenable to such a use case.

This is not directly related to your library, but I couldn't think of another way to reach out. Sorry if this is a bother, and you can resolve it ASAP and ignore it if you like 😆 .

For some additional context: https://github.com/orgs/syntax-tree/discussions/81

Thank you! 😄

**Comment by landakram** [comment]
I think it's a fine use-case - in my case I wrote the original plugin quite some time ago and I wanted either HTML output or AST specifically - I didn't care so much about transforming back into markdown.

If you want to transform back into markdown, I'd recommend having a look at https://github.com/landakram/mdast-util-wiki-link/, which will get you halfway there (Markdown -> AST). You will want to implement the other side, which would then go from the AST back to Markdown (converting the AST metadata about permalinks, etc. to regular markdown anchors). Hope that helps.

**Comment by aegatlin** [comment]
Great, thank you for the feedback :heart:

What you're saying makes a lot of sense given they way you structured your ast node. Sounds like there's an opportunity here to build some additional plugins.

(I have been staring at a lot of your code lately, and taking inspiration from it. Great work! 😄 )
