### ISSUE TITLE
Please specify licence

### ISSUE THREAD

**Issue by olayway** [landakram/remark-wiki-link#30]
Hello! Thank you for your amazing work! Since this project doesn't seem to be actively maintained I was wondering if I could build on and adjust your solution. I'm not sure if the project doesn't have LICENCE file on purpose, i.e. standard copy-right terms apply - in which case I'd have to write things from sratch, or it has just been omitted in the development process :)

I'd love to use your great code and I really hope you wouldn't mind :)

**Comment by landakram** [comment]
Hey @olayway, the project is licensed with MIT. See the LICENSE file here: https://github.com/landakram/remark-wiki-link/blob/master/LICENSE

Feel free to use how you wish according to the license! Always happy to review / merge a PR.

I will also point you to some work others have done to support obsidian style links: https://github.com/flowershow/remark-wiki-link-plus

**Comment by landakram** [comment]
Oh, just saw you're a contributor to flowershow... in any case, hope the clarification about license helps!
