### ISSUE TITLE
Support for customizing which characters can be used to determine the "name"

### ISSUE THREAD

**Issue by ChildishhAlbino** [landakram/remark-wiki-link#33]
Obsidian uses a bar character `|` for their resources aliases and I'd love to be use these instead of the colon icon `:`.

Is this something that's easily do-able? Very happy to tackle it myself regardless. 

Not sure if someone's barked up this tree already?

**Comment by landakram** [comment]
Does the aliasDivider (defaults to ":") option help you achieve what you want?

**Comment by ChildishhAlbino** [comment]
Honestly didn't know that was an option, let me try that and I'll let you know.

**Comment by ChildishhAlbino** [comment]
That worked a treat! Thanks for pointing that out :D

**Comment by Ainias** [comment]
@landakram I've tried to do the same and at first glance it is working. Unforunally inside tables the | is not working as separator. Do you have any tipps how I can achieve wiki-links with | as name separator inside tables? 

(Sorry for necro-posting. Should I open a new Issue with my question?)
