### ISSUE TITLE
Does not seem to register as wikilinks in remark 13

### ISSUE THREAD

**Issue by kangruixiang** [landakram/remark-wiki-link#8]
Hello I have recently updated to micromark with remark 13. However, wikilinks seem to not be registered as wikilinks. Example here:
https://runkit.com/kangruixiang/5f908ad22c9682001a7ccff6

Thank you.

**Comment by landakram** [comment]
Thanks for the heads up. As part of https://github.com/landakram/remark-wiki-link/pull/6, I changed the package to used named imports for better compatibility with ES6 modules.

So for CommonJS, you'll need to do:

```javascript
const { wikiLinkPlugin } = require('remark-wiki-link');
```

or

```javascript
const wikiLinkPlugin = require('remark-wiki-link').wikiLinkPlugin;
```

See this updated example which runs fine: https://runkit.com/5f90d0cdc9f246001a23af14/5f90d0d570a7ec001ae2e1d7

Apologies for not calling this out in the docs. I updated the code sample in the README to reflect this change. 

Let me know if you run into any further issues!
